In [ ]:
import os
import tensorflow as tf
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
# Directory with our training dandelion pictures
train_bpjs_dir = 'gdrive/MyDrive/validasi_suratrujukan/train/bpjs'

# Directory with our training grass pictures
train_bukan_dir = 'gdrive/MyDrive/validasi_suratrujukan/train/bukan'

# Directory with our validation dandelion pictures
valid_bpjs_dir = 'gdrive/MyDrive/validasi_suratrujukan/valid/bpjs'

# Directory with our validation grass pictures
valid_bukan_dir = 'gdrive/MyDrive/validasi_suratrujukan/valid/bukan'

In [ ]:
train_bpjs_names = os.listdir(train_bpjs_dir)
print(train_bpjs_names[:10])

train_bukan_names = os.listdir(train_bukan_dir)
print(train_bukan_names[:10])

validation_bpjs_hames = os.listdir(valid_bpjs_dir)
print(validation_bpjs_hames[:10])

validation_bukan_names = os.listdir(valid_bukan_dir)
print(validation_bukan_names[:10])

['12.jpg', '16.jpg', '17.jpg', '18.jpg', '10.jpg', '3.jpg', '4.jpg', '5.jpg', '1.jpg', '2.jpg']
['bukan_bpjs_0.jpg', 'bukan_bpjs_1.jpg', 'bukan_bpjs_2.jpg', 'bukan_bpjs_3.jpg', 'bukan_bpjs_4.jpg', 'bukan_bpjs_5.jpg', 'bukan_bpjs_6.jpg', 'bukan_bpjs_7.jpg', 'bukan_bpjs_8.jpg', 'bukan_bpjs_9.jpg']
['25.jpg', '26.jpg', '19.jpg', '20.jpg', '21.jpg', '22.jpg', '23.jpg', '24.jpg']
['bukan_bpjs_18.jpg', 'bukan_bpjs_19.jpg', 'bukan_bpjs_20.jpg', 'bukan_bpjs_21.jpg', 'bukan_bpjs_22.jpg', 'bukan_bpjs_23.jpg', 'bukan_bpjs_24.jpg', 'bukan_bpjs_25.jpg']


In [ ]:
print('total training bpjs images:', len(os.listdir(train_bpjs_dir)))
print('total training not bpjs images:', len(os.listdir(train_bukan_dir)))
print('total validation bpjs images:', len(os.listdir(valid_bpjs_dir)))
print('total validation not bpjs images:', len(os.listdir(valid_bukan_dir)))

total training bpjs images: 18
total training not bpjs images: 18
total validation bpjs images: 8
total validation not bpjs images: 8


In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_bpjs_fnames = os.listdir(train_bpjs_dir)
train_bukan_fnames = os.listdir(train_bukan_dir)

train_dir = 'gdrive/MyDrive/validasi_suratrujukan/train'
validation_dir = 'gdrive/MyDrive/validasi_suratrujukan/valid'

# Add our data-augmentation parameters to ImageDataGenerator
train_datagen = ImageDataGenerator(rescale = 1./255.)
# Note that the validation data should not be augmented!
test_datagen = ImageDataGenerator(rescale = 1.0/255.)

train_generator = train_datagen.flow_from_directory(train_dir,
                                                    batch_size = 1,
                                                    target_size = (150, 150))     

# Flow validation images in batches of 20 using test_datagen generator
validation_generator =  test_datagen.flow_from_directory(validation_dir,
                                                          batch_size  = 1,
                                                          target_size = (150, 150))

Found 36 images belonging to 2 classes.
Found 16 images belonging to 2 classes.


In [ ]:
validation_generator.class_indices

{'bpjs': 0, 'bukan': 1}

In [ ]:
from tensorflow import keras

tf.keras.backend.clear_session()
model = keras.Sequential()

# Convolutional layer and maxpool layer 1
model.add(keras.layers.Conv2D(32,(3,3),activation='relu',input_shape=(150,150,3)))
model.add(keras.layers.MaxPool2D(2,2))

# Convolutional layer and maxpool layer 2
model.add(keras.layers.Conv2D(64,(3,3),activation='relu'))
model.add(keras.layers.MaxPool2D(2,2))

# Convolutional layer and maxpool layer 3
model.add(keras.layers.Conv2D(128,(3,3),activation='relu'))
model.add(keras.layers.MaxPool2D(2,2))

# Convolutional layer and maxpool layer 4
model.add(keras.layers.Conv2D(128,(3,3),activation='relu'))
model.add(keras.layers.MaxPool2D(2,2))

# This layer flattens the resulting image array to 1D array
model.add(keras.layers.Flatten())

# Hidden layer with 512 neurons and Rectified Linear Unit activation function 
model.add(keras.layers.Dense(512,activation='relu'))

# Output layer with single neuron which gives 0 for Cat or 1 for Dog 
#Here we use sigmoid activation function which makes our model output to lie between 0 and 1
model.add(keras.layers.Dense(2, activation='softmax'))

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 148, 148, 32)      896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 74, 74, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 72, 72, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 36, 36, 64)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 34, 34, 128)       73856     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 17, 17, 128)       0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 15, 15, 128)       1

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate=0.0001)
model.compile(optimizer=optimizer,loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
model.fit_generator(train_generator,
         epochs = 10,
         validation_data = validation_generator)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:1940: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Epoch 1/10
36/36 [==============================] - 1s 13ms/step - loss: 0.2662 - accuracy: 0.8611 - val_loss: 0.0107 - val_accuracy: 1.0000
Epoch 2/10
36/36 [==============================] - 0s 10ms/step - loss: 0.0506 - accuracy: 1.0000 - val_loss: 0.0261 - val_accuracy: 1.0000
Epoch 3/10
36/36 [==============================] - 0s 10ms/step - loss: 0.0398 - accuracy: 1.0000 - val_loss: 0.0069 - val_accuracy: 1.0000
Epoch 4/10
36/36 [==============================] - 0s 10ms/step - loss: 0.0261 - accuracy: 1.0000 - val_loss: 0.0032 - val_accuracy: 1.0000
Epoch 5/10
36/36 [==============================] - 0s 10ms/step - loss: 0.0136 - accuracy: 1.0000 - val_loss: 0.0027 - val_accuracy: 1.0000
Epoch 6/10
36/36 [==============================] - 0s 10ms/step - loss: 0.0134 - accuracy: 1.0000 - val_loss: 0.0013 - val_accuracy: 1.0000
Epoch 7/10
36/36 [==============================] - 0s 10ms/step - loss: 0.0050 - accuracy: 1.0000 - val_loss: 0.0013 - val_accuracy: 1.0000
Epoch 8/10
36

In [ ]:
def predict(path):
    image_path = path

    img = tf.keras.preprocessing.image.load_img(
        image_path, target_size=(150, 150)
    )
    img_array = tf.keras.preprocessing.image.img_to_array(img)
    img_array = tf.expand_dims(img_array, 0) # Create a batch

    images = np.vstack([img_array])

    predictions = model.predict(images)

    print(predictions)

In [ ]:
predict("gdrive/MyDrive/validasi_suratrujukan/valid/bpjs/20.jpg")

[[1. 0.]]


In [ ]:
predict("gdrive/MyDrive/validasi_suratrujukan/train/bpjs/2.jpg")

[[1. 0.]]


In [ ]:
predict('Test1.jpg')

[[1. 0.]]


In [ ]:
predict('gdrive/MyDrive/validasi_suratrujukan/valid/bukan/bukan_bpjs_20.jpg')

[[0. 1.]]


In [ ]:
predict('pemandangan.png')

[[0. 1.]]


# **Save Model**

In [ ]:
model.save('gdrive/MyDrive/validasi_suratrujukan/model_model_tflite')

INFO:tensorflow:Assets written to: gdrive/MyDrive/validasi_suratrujukan/model_model_tflite/assets


In [ ]:
converter = tf.lite.TFLiteConverter.from_saved_model('gdrive/MyDrive/validasi_suratrujukan/model_oke') # path to the SavedModel directory
tflite_model = converter.convert()

# Save the model.
with open('gdrive/MyDrive/validasi_suratrujukan/model_oke_tflite/model.tflite', 'wb') as f:
  f.write(tflite_model)

# **TRANSFERLEARNING (belom kepake)**

In [ ]:
from tensorflow.keras import layers
from tensorflow.keras import Model

!wget --no-check-certificate \
    https://storage.googleapis.com/mledu-datasets/inception_v3_weights_tf_dim_ordering_tf_kernels_notop.h5 \
    -O /tmp/inception_v3_weights_tf_dim_ordering_tf_kernels_notop.h5
  
from tensorflow.keras.applications.inception_v3 import InceptionV3

local_weights_file = '/tmp/inception_v3_weights_tf_dim_ordering_tf_kernels_notop.h5'

pre_trained_model = InceptionV3(input_shape = (150, 150, 3), 
                                include_top = False, 
                                weights = None)

pre_trained_model.load_weights(local_weights_file)

for layer in pre_trained_model.layers:
  layer.trainable = False
  
pre_trained_model.summary()

last_layer = pre_trained_model.get_layer('mixed7')
print('last layer output shape: ', last_layer.output_shape)
last_output = last_layer.output

--2021-05-29 10:00:33--  https://storage.googleapis.com/mledu-datasets/inception_v3_weights_tf_dim_ordering_tf_kernels_notop.h5
Resolving storage.googleapis.com (storage.googleapis.com)... 74.125.199.128, 74.125.142.128, 74.125.195.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|74.125.199.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 87910968 (84M) [application/x-hdf]
Saving to: ‘/tmp/inception_v3_weights_tf_dim_ordering_tf_kernels_notop.h5’

/tmp/inception_v3_w 100%[===================>]  83.84M   135MB/s    in 0.6s    

2021-05-29 10:00:33 (135 MB/s) - ‘/tmp/inception_v3_weights_tf_dim_ordering_tf_kernels_notop.h5’ saved [87910968/87910968]

Model: "inception_v3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            [(None, 150, 150, 3) 0                  

In [ ]:
last_layer = pre_trained_model.get_layer('mixed3')
print('last layer output shape: ', last_layer.output_shape)
last_output = last_layer.output

last layer output shape:  (None, 7, 7, 768)


In [ ]:
from tensorflow.keras.optimizers import RMSprop

# Flatten the output layer to 1 dimension
x = layers.Flatten()(last_output)
# Add a fully connected layer with 1,024 hidden units and ReLU activation
x = layers.Dense(64, activation='relu')(x)
# Add a dropout rate of 0.2
x = layers.Dropout(0.2)(x)                  
# Add a final sigmoid layer for classification
x = layers.Dense  (1, activation='sigmoid')(x)           

model = Model( pre_trained_model.input, x) 

model.compile(optimizer = tf.optimizers.Adam(), 
              loss = 'binary_crossentropy', 
              metrics = ['accuracy'])

In [ ]:
model.summary()

Model: "model_11"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            [(None, 150, 150, 3) 0                                            
__________________________________________________________________________________________________
conv2d_98 (Conv2D)              (None, 74, 74, 32)   864         input_2[0][0]                    
__________________________________________________________________________________________________
batch_normalization_94 (BatchNo (None, 74, 74, 32)   96          conv2d_98[0][0]                  
__________________________________________________________________________________________________
activation_94 (Activation)      (None, 74, 74, 32)   0           batch_normalization_94[0][0]     
___________________________________________________________________________________________

In [ ]:
history = model.fit_generator(
            train_generator,
            validation_data = validation_generator,
            epochs=5)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:1940: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Epoch 1/5
36/36 [==============================] - 2s 26ms/step - loss: 5.0072 - accuracy: 0.6111 - val_loss: 5.4703 - val_accuracy: 0.5000
Epoch 2/5
36/36 [==============================] - 1s 15ms/step - loss: 1.9977 - accuracy: 0.8889 - val_loss: 1.7265e-07 - val_accuracy: 1.0000
Epoch 3/5
36/36 [==============================] - 1s 15ms/step - loss: 0.6827 - accuracy: 0.8611 - val_loss: 5.9572e-09 - val_accuracy: 1.0000
Epoch 4/5
36/36 [==============================] - 1s 15ms/step - loss: 1.4801 - accuracy: 0.8611 - val_loss: 3.2295e-11 - val_accuracy: 1.0000
Epoch 5/5
36/36 [==============================] - 1s 15ms/step - loss: 1.9563e-04 - accuracy: 1.0000 - val_loss: 2.4174e-10 - val_accuracy: 1.0000


In [ ]:
predict("gdrive/MyDrive/validasi_suratrujukan/valid/bpjs/20.jpg")

[[0.]]


In [ ]:
predict("gdrive/MyDrive/validasi_suratrujukan/valid/bukan/bukan_bpjs_20.jpg")

[[1.]]


In [ ]:
predict('test.png')

[[1.]]


In [ ]:
converter = tf.lite.TFLiteConverter.from_saved_model('gdrive/MyDrive/validasi_suratrujukan/model_ringan') # path to the SavedModel directory
tflite_model = converter.convert()

# Save the model.
with open('gdrive/MyDrive/validasi_suratrujukan/model_ringan/model.tflite', 'wb') as f:
  f.write(tflite_model)

In [ ]:
new_model = tf.keras.models.load_model('gdrive/MyDrive/validasi_suratrujukan/model')